// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuck-oKSlU81_E6RQa6DMPoB71cGNYMMQ',
    appId: '1:863081427842:web:c1021c299733703614559b',
    messagingSenderId: '863081427842',
    projectId: 'couplink-17882',
    authDomain: 'couplink-17882.firebaseapp.com',
    storageBucket: 'couplink-17882.firebasestorage.app',
    measurementId: 'G-69F0NZRSQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTsK_kiWvU87DeUcesM-Wy-JQIFG3_Vk',
    appId: '1:863081427842:android:21c271c0f736abe214559b',
    messagingSenderId: '863081427842',
    projectId: 'couplink-17882',
    storageBucket: 'couplink-17882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX10_jyJgNBn6k6QCwyeD80t4G3lF33W0',
    appId: '1:863081427842:ios:10aa65a3c5652a7514559b',
    messagingSenderId: '863081427842',
    projectId: 'couplink-17882',
    storageBucket: 'couplink-17882.firebasestorage.app',
    iosBundleId: 'com.couplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX10_jyJgNBn6k6QCwyeD80t4G3lF33W0',
    appId: '1:863081427842:ios:c19d9f1ff6846fad14559b',
    messagingSenderId: '863081427842',
    projectId: 'couplink-17882',
    storageBucket: 'couplink-17882.firebasestorage.app',
    iosBundleId: 'com.example.couplinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuck-oKSlU81_E6RQa6DMPoB71cGNYMMQ',
    appId: '1:863081427842:web:a4b58e5949946c7c14559b',
    messagingSenderId: '863081427842',
    projectId: 'couplink-17882',
    authDomain: 'couplink-17882.firebaseapp.com',
    storageBucket: 'couplink-17882.firebasestorage.app',
    measurementId: 'G-MPX9Q2NSS5',
  );
}
